---

- name: Install nvm
  git:
    repo: "https://github.com/creationix/nvm.git"
    dest: "{{ home }}/.nvm"
    version: "{{ nvm.version }}"
  tags: nvm
  become: true
  become_user: "{{ user_name }}"

- name: Install node and set version
  shell: /bin/bash -c 'source {{ home }}/.nvm/nvm.sh && [ "$(type -t nvm)" == "function" ] && [ "$(nvm current)" == "{{node.version}}" ] && echo "nvm already setup" || nvm install {{node.version}}'
  become: true
  become_user: "{{ user_name }}"

#- name: Create npm global directory
#  file:
#    path: "{{ npm_config_prefix }}"
#    owner: "{{ nodejs_install_npm_user }}"
#    group: "{{ nodejs_install_npm_user }}"
#    state: directory

- name: Ensure npm global packages are installed.
  shell: /bin/bash -c 'source {{ home }}/.nvm/nvm.sh && {{ home }}/.nvm/versions/node/{{ node.version }}/bin/npm install -g {{ npm_packages | join(' ') }}'
  # npm:
    # name: "{{ item.name }}"
    # global: yes
    # state: latest
    # executable: "{{ home }}/.nvm/versions/node/{{ node.version }}/bin/node"
  # with_items: "{{ npm_packages }}"
  # become: false
