---

- name: Install nvm
  git:
    repo: "https://github.com/creationix/nvm.git"
    dest: "{{ home }}/.nvm"
    version: "{{ nvm.version }}"
  tags: nvm
  become: true
  become_user: "{{ user_name }}"

#- name: Install node and set version
#  shell:
#    /bin/bash -c "source {{ home }}/.nvm/nvm.sh && if [ "$(type -t nvm)" == "function" ] && [ "$(nvm current)" == "system" ]; then echo "nvm already setup"; else nvm install 0.12.18 fi"
#  become: true
#  become_user: "{{ user_name }}"

#- name: Create npm global directory
#  file:
#    path: "{{ npm_config_prefix }}"
#    owner: "{{ nodejs_install_npm_user }}"
#    group: "{{ nodejs_install_npm_user }}"
#    state: directory

- name: Ensure npm global packages are installed.
  npm:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default('latest') }}"
    global: yes
    state: latest
#  environment:
#    NPM_CONFIG_PREFIX: "{{ npm_config_prefix }}"
#    NODE_PATH: "{{ npm_config_prefix }}/lib/node_modules"
#    NPM_CONFIG_UNSAFE_PERM: "{{ npm_config_unsafe_perm }}"
  with_items: "{{ npm_packages }}"
