---

- name: add login item
  command: "loginitems -a '{{ item }}'"
  changed_when: false
  with_items: "{{ startup_login_items }}"

- name: download asana
  get_url:
    url: https://www.dropbox.com/sh/di4kmus56l6pbgi/AADtiWjIGs9GiV5uHGRCC8wXa?dl=1
    dest: /Applications/Asana.app
    mode: '0755'

- name: Ensure python pip packages are installed.
  shell: /bin/bash -c 'pip3 install {{ pip_packages | join(' ') }}'