---

- hosts: macbox
  connection: local
  roles:
    - etchosts
    - homebrew
    - bash
    - fasd
    - aliases
    - functions
    - git
    - node
    - emacs
    - tmux
    - ssh #id_rsa key generation
    - dockutil
    - mas
    - iterm2

  become: yes
  become_method: sudo

  vars:
    user_name: gleitz
    user_group: staff
    home: "~"
    roles_dir: "{{ home }}/.files/ansible/roles"
    id_rsa: "{{ home }}/.ssh/id_rsa"

    filevault_auto_evict: true

    homebrew_cask_require_sha: false
    homebrew_taps:
      - homebrew/core
      - wooga/unityversions
      - j1mr10rd4n/homebrew-tap
    homebrew_installed_packages:
      - aspell
      - bash
      - bash-completion
      - blackbox
      - daemontools
      - docker-compose
      - dockutil
      - ffmpeg
      - fzf
      - geth
      - git-lfs
      - ipython
      - imagemagick
      - kubectl
      - markdown
      - mas
      - meteor
      # - mongodb
      - mp3wrap
      - node
      - openssl
      - postgresql
      - python
      - python3
      - rename
      - ruby
      - sox
      - stack
      - thefuck
      - the_silver_searcher
      - tmux
      - wget
      - yarn
    homebrew_cask_apps:
      - 1password
      - alfred
      - android-file-transfer
      - android-studio
      - arduino
      - bettertouchtool
      - caffeine
      - calibre
      - carbon-copy-cloner
      - clipgrab
      - cockatrice
      - daisydisk
      - dashlane
      - docker
      - dropbox
      - emacs
      - enjoyable
      - fantastical
      - firefox
      - flux
      - fspviewer
      - google-chrome
      - handbrake
      - hazel
      - insertpic
      - intel-power-gadget
      - istat-menus
      - iterm2
      - java8
      - krisp
      - muzzle
      - ngrok
      - playonmac
      - postico
      - postman
      - prey
      - rekordbox
      - remember-the-milk
      - robo-3t
      - rq
      - sabnzbd
      - scidvsmac
      - screenflow
      - sequel-pro
      - skitch
      - skype
      - slack
      - soundflower
      - sketch
      - spotify
      - steam
      - studio-3t
      - timemachineeditor
      - transmission
      - android-support-for-editor
      - unrarx
      - viscosity
      - virtualbox
      - vlc
      - whatsapp
      - xact
      - xquartz
      - yakyak
      - zoomus

    pip_packages:
      - name: howdoi
      - name: jedi
      - name: jupyter
      - name: pylint
      - name: rst2html5
      - name: virtualenvwrapper

    npm_packages:
      - name: mupx
      - name: jshint
      - name: jsxhint
      - name: tern
      - name: trash-cli
      - name: soundscrape
      - name: eslint
      - name: babel-eslint
      - name: eslint-plugin-react
      - name: create-react-app
      - name: tslint
      - name: typescript
      - name: pm2
      - name: grunt-cli
      - name: forever
      - name: serve

    ruby_gems:
      - name: rumember

    mas_email: ""
    mas_password: ""
    mas_installed_apps:
      - { id: 1053031090, name: "Boxy" }
      - { id: 411213048, name: "LadioCast" }
    mas_upgrade_all_apps: no
    mas_signin_dialog: yes

    dockitems_to_persist:
      - name: Google Chrome
        path: "/Applications/Google Chrome.app"
        pos: 2
      - name: iTerm
        path: "/Applications/iTerm.app"
        pos: 3
      - name: Spotify
        path: "/Applications/Spotify.app"
        pos: 4
      - name: Emacs
        path: "/Applications/Emacs.app"
        pos: 5
      - name: Boxy
        path: "/Applications/Boxy.app"
        pos: 6
      - name: Slack
        path: "/Applications/Slack.app"
        pos: 7
      - name: WhatsApp
        path: "/Applications/WhatsApp.app"
        pos: 8
      - name: YakYak
        path: "/Applications/YakYak.app"
        pos: 9
      - name: Remember The Milk
        path: "/Applications/Remember The Milk.app"
        pos: 10
      - name: Fantastical 2
        path: "/Applications/Fantastial 2.app"
        pos: 11
