---

- hosts: macbox
  connection: local
  roles:
    - etchosts
    - homebrew
    - bash
    - zsh
    - fasd
    - aliases
    - functions
    - git
    - node
    - emacs
    - tmux
    - ssh #id_rsa key generation
    - dockutil
    - mas
    # - macos
    - iterm2

  become: yes
  become_method: sudo

  vars:
    user_name: gleitz
    user_group: staff
    home: "~"
    roles_dir: "{{ home }}/.files/ansible/roles"
    id_rsa: "{{ home }}/.ssh/id_rsa"

    filevault_auto_evict: true

    homebrew_cask_require_sha: false
    homebrew_taps:
      - homebrew/core
      - caskroom/cask
      - caskroom/versions
    homebrew_installed_packages:
      # - antibody
      # - cheat
      # - fasd    # separate role
      # - gnupg2  # requires java...
      # - mas
      # - privoxy # separate role
      # - syncthing
      # - tldr
      - bash
      - bash-completion
      - blackbox
      - daemontools
      - dockutil
      - geth
      - git-lfs
      # - htop
      - imagemagick
      - kubectl
      - markdown
      - mas
      # - mongodb
      - node
      - openssl
      - postgresql
      - python
      - python3
      - ruby
      - stack
      - the_silver_searcher
      - tmux
      - wget
      - yarn
    homebrew_cask_apps:
      - 1password
      - alfred
      - android-file-transfer
      - android-studio
      - arduino
      - bettertouchtool
      - caffeine
      - calibre
      - carbon-copy-cloner
      - cockatrice
      - dashlane
      - docker
      - dropbox
      - emacs
      - enjoyable
      - fantastical
      - flux
      - fspviewer
      - google-chrome
      - handbrake
      - hazel
      - insertpic
      - istat-menus
      - iterm2
      - ngrok
      - playonmac
      - postico
      - postman
      - rekordbox
      - remember-the-milk
      - robo-3t
      - rq
      - scidvsmac
      - screenflow
      - skitch
      - skype
      - slack
      - spotify
      - steam
      - studio-3t
      - transmission
      - unrarx
      - viscosity
      - virtualbox
      - vlc
      - whatsapp
      - xact
      - xquartz
      - yakyak
      - zoomus

    pip_packages:
      - name: pylint
      - name: virtualenvwrapper
      - name: howdoi

    npm_packages:
      - name: mupx
      - name: jshint
      - name: jsxhint
      - name: tern
      - name: phantomjs
      - name: soundscrape
      - name: eslint
      - name: babel-eslint
      - name: avn
      - name: avn-nvm
      - name: avn-n
      - name: eslint-plugin-react
      - name: create-react-app
      - name: tslint
      - name: typescript
      - name: pm2
      - name: grunt-cli
      - name: forever
      - name: serve
        
    mas_email: ""
    mas_password: ""
    mas_installed_apps:
      - { id: 1053031090, name: "Boxy" }
    mas_upgrade_all_apps: no
    mas_signin_dialog: yes

    dockitems_to_persist:
      - name: Google Chrome
        path: "/Applications/Google Chrome.app"
        pos: 2
      - name: iTerm
        path: "/Applications/iTerm.app"
        pos: 3
      - name: Spotify
        path: "/Applications/Spotify.app"
        pos: 4
      - name: Emacs
        path: "/Applications/Emacs.app"
        pos: 5
      - name: Boxy
        path: "/Applications/Boxy.app"
        pos: 6
      - name: Slack
        path: "/Applications/Slack.app"
        pos: 7
      - name: WhatsApp
        path: "/Applications/WhatsApp.app"
        pos: 8
      - name: YakYak
        path: "/Applications/YakYak.app"
        pos: 9
      - name: Remember The Milk
        path: "/Applications/Remember The Milk.app"
        pos: 10
      - name: Fantastical 2
        path: "/Applications/Fantastial 2.app"
        pos: 11
