---

- hosts: macbox
  connection: local
  roles:
    - etchosts
    - node
    - homebrew
    - bash
    - fasd
    - aliases
    - functions
    - git
    - ruby
    - emacs
    - various
    - tmux
    - ssh #id_rsa key generation
    - dockutil
    - mas
    - iterm2

  become: yes
  become_method: sudo
  ignore_errors: true

  vars:
    user_name: gleitz
    user_group: staff
    home: "~"
    roles_dir: "{{ home }}/.files/ansible/roles"
    id_rsa: "{{ home }}/.ssh/id_rsa"

    filevault_auto_evict: true

    homebrew_cask_require_sha: false
    homebrew_taps:
      - homebrew/core
      - wooga/unityversions
      - j1mr10rd4n/homebrew-tap
      - derailed/k9s
      - OJFord/formulae
    homebrew_installed_packages:
      - aspell
      - bash
      - bash-completion@2
      - bfg
      - blackbox
      - daemontools
      - docker-compose
      - dockutil
      - fasd
      - ffmpeg
      - fzf
      - geth
      - git-lfs
      - gnu-tar
      - hyperfine
      - ipython
      - imagemagick
      - k9s
      - kubectl
      - loginitems
      - markdown
      - mas
      # - mongodb
      - moreutils
      - mp3wrap
      - nmap
      - openssl
      - postgresql
      - python
      - redis
      - rename
      - ripgrep
      - ruby
      - sox
      - stack
      - thefuck
      - tldr
      - tmux
      - wget
    homebrew_cask_apps:
      - 1password
      - adobe-digital-editions
      - airfoil
      - alfred
      - android-file-transfer
      - arduino
      - bettertouchtool
      - boxy-suite
      - burn
      - caffeine
      - calibre
      - carbon-copy-cloner
      - clipgrab
      - cockatrice
      - coconutbattery
      - daisydisk
      - discord
      - docker
      - dropbox
      - emacs
      - enjoyable
      - fantastical
      - firefox
      - flux
      - google-chrome
      - handbrake
      - hazel
      - istat-menus
      - iterm2
      - jq
      - launchcontrol
      - loopback
      - muzzle
      - ngrok
      - postico
      - postman
      - rekordbox
      - remember-the-milk
      - robo-3t
      - rq
      - sabnzbd
      - screenflow
      - signal
      - skitch
      - skype
      - slack
      - sketch
      - spotify
      - steam
      - studio-3t
      - switchresx
      - tableau
      - tableplus
      - the-unarchiver
      - transmission
      - unrarx
      - viscosity
      - visual-studio
      - virtualbox
      - vlc
      - whatsapp
      - xact
      - xquartz
      - zoomus

    pip_packages:
      - elpy
      - epc
      - flake8
      - howdoi
      - jedi
      - jupyter
      - mypy
      - pylint
      - requests
      - rst2html5
      - virtualenvwrapper

    npm_packages:
      - babel-eslint
      - create-react-app
      - eslint
      - eslint-plugin-react
      - forever
      - gatsby-cli
      - grunt-cli
      - jshint
      - jsxhint
      - npx
      - npm-check-updates
      - prettier
      - pm2
      - rtm-cli
      - serve
      - tern
      - trash-cli
      - typescript

#    ruby_gems:
#      - name: rumember

    mas_email: ""
    mas_password: ""
    mas_installed_apps:
      - { id: 409183694, name: "Keynote" }
      - { id: 453114608, name: "JSON Helper" }
      - { id: 1182646052, name: "Remote Control for LIFX" }
      - { id: 488536386, name: "Location Helper" }
      - { id: 411213048, name: "LadioCast" }
    mas_upgrade_all_apps: no
    mas_signin_dialog: yes

    dockitems_to_persist:
      - name: Google Chrome
        path: "/Applications/Google Chrome.app"
        pos: 2
      - name: iTerm
        path: "/Applications/iTerm.app"
        pos: 3
      - name: Emacs
        path: "/Applications/Emacs.app"
        pos: 4
      - name: Spotify
        path: "/Applications/Spotify.app"
        pos: 5
      - name: Boxy for Gmail
        path: "/Applications/Boxy for Gmail.app"
        pos: 6
      - name: Signal
        path: "/Applications/Signal.app"
        pos: 7
      - name: Slack
        path: "/Applications/Slack.app"
        pos: 8
      - name: Discord
        path: "/Applications/Discord.app"
        pos: 9
      - name: Boxy for Calendar
        path: "/Applications/Boxy for Calendar.app"
        pos: 10
      - name: Fantastical 2
        path: "/Applications/Fantastical 2.app"
        pos: 11
      - name: Remember The Milk
        path: "/Applications/Remember The Milk.app"
        pos: 12
      - name: TablePlus
        path: "/Applications/TablePlus.app"
        pos: 13
